### PR TITLE
Removed Boost dependency.

### PR DESCRIPTION
**Pull request by billyquith**
Hi, I've removed CAMP's dependency on Boost (apart from the unit tests). Only C++11 is used now. Compile times should be a bit faster. Let me know if you have any problems.

I realise this may be a problem for older compilers that don't support C++11 that rely on Boost, but IMHO the library can be simplified somewhat by relying on things like variadic templates etc, and there is good C++11 support in GCC, clang, MSVC.

Cheers!

### CODE REVIEW

**Comment by billyquith** [comment]
@LaurentGomila Hi there, wondered if you guys had seen this change. Thanks.

**Comment by LaurentGomila** [comment]
I made a quick review of your PR when you posted it, and Frederic was supposed to answer you... He probably forgot, as usual :)

Anyway, here is what I think about it. Adapting CAMP to C++11 involves rewriting almost everything, as we can see in this huge PR. Since this project is not actively maintained anymore, we can't fully review your code, test it and maintain it properly. You also didn't follow our coding conventions. Which brings me to the conclusion that we really shouldn't merge your work, you should instead publish your own fork and maintain it separately from the original project -- which is dead anyway.

**Comment by billyquith** [comment]
> You also didn't follow our coding conventions.
How so?

Ok, well that makes sense. A link to the fork would be nice, in case others want to use or continue development. A fork is whole new project.

**Comment by FredericLeuba** [comment]
Hello Nick, nice to hear from you. Thanks for your good wishes! I hope you had a merry Christmas and wish you an happy new year.

As Laurent nicely told you… I tend to forget things … * sometimes * (sic) … your e-mail was lost among the pool of flagged e-mails.
I fully agree with Laurent's opinion, the changes you’ve done are huge, your project deserve a brand new life, and you deserve credits on your own :-)
We’ll add a link to your fork where we can and mention your switch to C++11.

Best regards
Fred

**Comment by billyquith** [comment]
No, worries. A very Merry Xmas :santa: and Happy New Year :balloon: to you guys as well! :smile:

I called the new library "[Ponder](https://github.com/billyquith/ponder)". It is a mirror/duplicate of CAMP so should be a true fork.

Cheers!

**Pull request closed without merging**
